# Generated by Django 3.2.7 on 2021-11-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(default=' ', upload_to='img/pics')),
            ],
        ),
    ]
