# Generated by Django 3.2.7 on 2021-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(default=' ', upload_to='img/pics')),
            ],
        ),
    ]
